[package]
name = "escpos-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = { version = "4.0.1", default-features = false }
bitflags = "1.3.2"
