[package]
name = "print-bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
escpos-lib = { path = "../escpos-lib" }
structopt = "0.3.23"
serialport = "4.0.1"
